-- Nutrient table
CREATE TABLE nutrient (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at  TIMESTAMPTZ(6),
    updated_at  TIMESTAMPTZ(6),
    "name"      VARCHAR(255) NOT NULL,
    unit        VARCHAR(255) NOT NULL,
    CONSTRAINT nutrient_pkey PRIMARY KEY (id)
);

-- Product table
CREATE TABLE product (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at  TIMESTAMPTZ(6),
    updated_at  TIMESTAMPTZ(6),
    fdc_id      INTEGER NOT NULL,
    "name"      VARCHAR(255) NOT NULL,
    CONSTRAINT product_pkey PRIMARY KEY (id),
    CONSTRAINT uk_product_fdc_id UNIQUE (fdc_id)
);

-- Users table
CREATE TABLE users (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at  TIMESTAMPTZ(6),
    updated_at  TIMESTAMPTZ(6),
    email       VARCHAR(255),
    enabled     BOOLEAN NOT NULL,
    "password"  VARCHAR(255),
    username    VARCHAR(255),
    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT uk_users_email    UNIQUE (email),
    CONSTRAINT uk_users_username UNIQUE (username)
);

-- Menu table
CREATE TABLE menu (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at     TIMESTAMPTZ(6),
    updated_at     TIMESTAMPTZ(6),
    days           INTEGER NOT NULL,
    meals          INTEGER NOT NULL,
    "name"         VARCHAR(100) NOT NULL,
    start_date     DATE NOT NULL,
    target_carb    REAL NOT NULL,
    target_fat     REAL NOT NULL,
    target_protein REAL NOT NULL,
    owner_id       BIGINT NOT NULL,
    CONSTRAINT menu_pkey PRIMARY KEY (id),
    CONSTRAINT fk_menu_owner FOREIGN KEY (owner_id) REFERENCES users (id)
);

-- Product_nutrient table
CREATE TABLE product_nutrient (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at   TIMESTAMPTZ(6),
    updated_at   TIMESTAMPTZ(6),
    amount       DOUBLE PRECISION NOT NULL,
    nutrient_id  BIGINT NOT NULL,
    product_id   BIGINT NOT NULL,
    CONSTRAINT product_nutrient_pkey PRIMARY KEY (id),
    CONSTRAINT fk_product_nutrient_product  FOREIGN KEY (product_id)  REFERENCES product (id),
    CONSTRAINT fk_product_nutrient_nutrient FOREIGN KEY (nutrient_id) REFERENCES nutrient (id)
);

-- User_roles table
CREATE TABLE user_roles (
    user_id BIGINT NOT NULL,
    roles   VARCHAR(255),
    CONSTRAINT fk_user_roles_user FOREIGN KEY (user_id) REFERENCES users (id)
);

-- Verification_token table
CREATE TABLE verification_token (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at      TIMESTAMPTZ(6),
    updated_at      TIMESTAMPTZ(6),
    expiration_date TIMESTAMPTZ(6) NOT NULL,
    "token"         VARCHAR(255) NOT NULL,
    user_id         BIGINT NOT NULL,
    CONSTRAINT verification_token_pkey PRIMARY KEY (id),
    CONSTRAINT uk_verification_token_user UNIQUE (user_id),
    CONSTRAINT fk_verification_token_user FOREIGN KEY (user_id) REFERENCES users (id)
);

-- Meal table
CREATE TABLE meal (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at  TIMESTAMPTZ(6),
    updated_at  TIMESTAMPTZ(6),
    "date"      DATE,
    "name"      VARCHAR(255) NOT NULL,
    target_kcal INTEGER NOT NULL,
    menu_id     BIGINT NOT NULL,
    CONSTRAINT meal_pkey PRIMARY KEY (id),
    CONSTRAINT fk_meal_menu FOREIGN KEY (menu_id) REFERENCES menu (id)
);

-- Meal_item table
CREATE TABLE meal_item (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMPTZ(6),
    updated_at TIMESTAMPTZ(6),
    amount     DOUBLE PRECISION NOT NULL,
    meal_id    BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    CONSTRAINT meal_item_pkey PRIMARY KEY (id),
    CONSTRAINT fk_meal_item_product FOREIGN KEY (product_id) REFERENCES product (id),
    CONSTRAINT fk_meal_item_meal    FOREIGN KEY (meal_id)    REFERENCES meal (id)
);
